c'est une proposition de correction/refactoring
Guuzii/Nest-api-template pull request #12
Opened 2023-10-09 09:17 UTC by VincentProuchet

UserEntity
User-get.dto
  modification des propriètées pour permettre une valeur null
  à celle acceptées par la base de données

user.service
  lors du changement de mot de passe dans une procédure forgotpwd
  le token resetPwdToken est mit à null au lieu de undefined
  car undefined n'est pas reconnu par les bases de données
  et typeORM ne semble pas faire la conversion

2023-10-09 11:05 UTC, Guuzii requested changes

2023-10-09 11:05 UTC, Guuzii commented on src/user/dto/out/user-get.dto.ts
> +  firstname: string | null;
if faudrait remettre les "?" dans l'interface pour rendre les propriété optionnelles

2023-10-09 11:05 UTC, Guuzii commented on src/user/dto/out/user-get.dto.ts
> +  email?: string;
la propriété email de doit pas être optionnelle, retirer le "?"

2023-10-09 11:05 UTC, Guuzii commented on src/user/entities/user.entity.ts
Même chose que pour le dto, il faut laisser les propriétés optionelles (remettre les "?")

2023-10-10 12:20 UTC, VincentProuchet commented on src/user/entities/user.entity.ts
modifications demandées faites et push

2023-10-10 12:21 UTC, VincentProuchet commented on src/user/dto/out/user-get.dto.ts
> +  email?: string;
modification demandée faite et push

2023-10-10 13:32 UTC, Guuzii approved these changes

2023-10-10 13:32 UTC, merged